TrainReader:
  reader_function: ppocr.data.rec.dataset_traversal,SimpleReader
  num_workers: 8
  img_set_dir: .
  label_file_path: ./HanddleOCR/gt_train.txt
  
EvalReader:
  reader_function: ppocr.data.rec.dataset_traversal,SimpleReader
  img_set_dir: .
  label_file_path: ./HanddleOCR/gt_val.txt

TestReader:
  reader_function: ppocr.data.rec.dataset_traversal,SimpleReader
